services:
  app:
    build:
      # use local image
      dockerfile: Dockerfile
      context: .
    container_name: emmett_api
    profiles: [app]
    environment:
      - SQLITE_FILENAME=file:./emmett_event_store.db
    networks:
      - postgresql_network
    ports:
      - '3000:3000'
