name: Publish to NPM
on: [workflow_dispatch]

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"
          node-version-file: ./src/.nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Set public publishing
        run: npm config set access public

      - name: Publish package on NPM ðŸ“¦
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"beta"* ]]; then
            TAG="beta"
          elif [[ $VERSION == *"alpha"* ]]; then
            TAG="alpha"
          elif [[ $VERSION == *"rc"* ]]; then
            TAG="rc"
          else
            TAG="latest"
          fi
          npm publish --ws --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production
